# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.5
  - 3.8

env:
  - TOXENV=django22
  - TOXENV=quality
  - TOXENV=docs

cache:
  - pip
  
before_install:
  - pip install pip==20.0.2

install:
  - pip install -r requirements/ci.txt

script:
  - tox

after_success:
  - codecov

# Set password via "travis encrypt --add deploy.password"; for details, see
# https://docs.travis-ci.com/user/deployment/pypi
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    python: "3.5"
    tags: true
    condition: '$TOXENV = quality'
  password:
    secure: js1FSGQYpJfwOXAox8zermm7yyHkqko2PxzimKLc6RcefCHngBaFelm9y0Ry33JDNhHNk4Hb9ilIaGPckQSsY7nifV9UuC2IjpHxMhCXPLGahgKnkckZEZBxSMjl8+rxJTQhhGA2AlAXmdwKt5OLu8EJtF+oiTyKnx7BhngjU01Ldw9ozflMAeNVbnRIjZpBV0Rtpru+TPtyqE7/L5h2tsnNyVJwQvPQ13EC0keLtb1sdMR2YUgAv23CPha7CRqj0sNYJIslhzLjD+BbQGOy7RTj187wIl3EE4kuSWITE64Kuye5rC75CAzzZ7rfVtN4ilrBe1qM2GhMltFZ/0sVn0CIn/Qy9pJK8K2kND1rJxsFQArsOkWc7Ykz9ytY9EpeEQgKkhU2GqzpRGG/71EkIXk9I3bgPDLevZ5NLSxR9Zn0xexLt2RuyqC1g5+BgUcsPqnQatOyLhvTFWQ0byAXxVTaZkWtSRp7DN2DARq+V0Vg2hoiM6jYPyjCUsHctl/Fb9F0q8O7MwYiI8nObVj9EoWV8+77Rn2H8pPgWH31apjXRR02vzKsFt6gIwrq5YbGwvSnePXeUVLBilNKQ6EXsdakWuCWmj1FajITcBcR4UKWZRlIG0mjRfcUkBofheVqfCaZqMt3bFf4gyE1Jj62vzXX+BU5SXEV2al5PZahEqA=
